//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class smsEntities : DbContext
    {
        public smsEntities()
            : base("name=smsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productbrand> productbrands { get; set; }
        public virtual DbSet<productcategory> productcategories { get; set; }
        public virtual DbSet<producttype> producttypes { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<user> users { get; set; }

		public List<product> getProducts()
		{
			return products.ToList();
		}
    }
}
