//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int StkID { get; set; }
        public double Qty { get; set; }
        public string UOM { get; set; }
        public int Price { get; set; }
        public int Product { get; set; }
    
        public virtual product product1 { get; set; }
    }
}
