//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UID { get; set; }
        public string Name { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Mac { get; set; }
        public int Role { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Contact { get; set; }
    
        public virtual role role1 { get; set; }
    }
}
